name: Build and Release Action

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install NCC
        run: npm install -g @vercel/ncc

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:action

      - name: Publish GitHub Action
        run: git add dist && git commit -m "Update dist" && git push origin main

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
