name: Build and Release Action

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install NCC
        run: npm install -g ncc && npm install && npm run build:action

      - name: Publish GitHub Action
        run: git push origin main
