name: Build and Release Action

on:
  push:
    tags:
      - 'v*'  # Run when a version tag (e.g., v1.0.0) is pushed
  workflow_dispatch:

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install NCC
        run: npm install -g @vercel/ncc

      - name: Install dependencies
        run: npm install

      - name: Remove old index.js
        run: rm -f gludoc/index.js

      - name: Build
        run: npm run build:action

      - name: Check for changes in gludoc
        id: changes_check
        run: |
          lines_changed=$(git status -s | wc --lines)
          echo "has_changes=$lines_changed" >> $GITHUB_OUTPUT

      - name: Publish GitHub Action
        if: steps.changes_check.outputs.has_changes != '0'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add gludoc -f
          git commit -m "Auto-build GitHub Action" &&
          git push origin main
