name: Generate new tag if needed

on:
  push:
    branches:
      - main

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read latest tag
        id: latest_tag
        run: |
          echo "latest_tag=$(git describe --tags --abbrev=0 || echo 'none')" >> $GITHUB_ENV

      - name: Read version from package.json
        id: version
        run: |
          echo "version=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: Generate new tag if needed
        if: env.version != env.latest_tag
        run: |
          new_tag="v${{ env.version }}"
          echo "Generating new tag: $new_tag"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $new_tag
          git push origin $new_tag
        env:
          version: ${{ env.version }}
          latest_tag: ${{ env.latest_tag }}
